removed test reports from PR, because they do not work when PRs are submitted from forks

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -35,8 +35,6 @@ jobs:
     needs: build-cache
     permissions:
       checks: write
-      contents: read
-      actions: read
     services:
       postgres:
         image: postgres
@@ -56,7 +54,7 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-addons -n 1 --junit
     - name: Upload report
-      if: success() || failure()    # run this step even if previous step failed
+      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
 
   website:
@@ -64,8 +62,6 @@ jobs:
     needs: build-cache
     permissions:
       checks: write
-      contents: read
-      actions: read
     services:
       postgres:
         image: postgres
@@ -86,7 +82,7 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-website -n 1 --junit
     - name: Upload report
-      if: success() || failure()    # run this step even if previous step failed
+      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
 
   api1_and_js:
@@ -94,8 +90,6 @@ jobs:
     needs: build-cache
     permissions:
       checks: write
-      contents: read
-      actions: read
     services:
       postgres:
         image: postgres
@@ -119,7 +113,7 @@ jobs:
       - name: Run test
         run: python3 -m invoke test-travis-api1-and-js -n 1 --junit
       - name: Upload report
-        if: success() || failure()    # run this step even if previous step failed
+        if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
         uses: ./.github/actions/gen-report
 
   api2:
@@ -127,8 +121,6 @@ jobs:
     needs: build-cache
     permissions:
       checks: write
-      contents: read
-      actions: read
     services:
       postgres:
         image: postgres
@@ -148,15 +140,13 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-api2 -n 1 --junit
     - name: Upload report
-      if: success() || failure()    # run this step even if previous step failed
+      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
 
   api3_and_osf:
     runs-on: ubuntu-20.04
     permissions:
       checks: write
-      contents: read
-      actions: read
     needs: build-cache
     services:
       postgres:
@@ -178,5 +168,5 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-api3-and-osf -n 1 --junit
     - name: Upload report
-      if: success() || failure()    # run this step even if previous step failed
+      if: (github.event_name != 'pull_request') && (success() || failure())    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
