added permission for test reporter to alter actions

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -33,10 +33,11 @@ jobs:
   addons:
     runs-on: ubuntu-20.04
     needs: build-cache
+    permissions:
+      checks: write
     services:
       postgres:
         image: postgres
-
         env:
           POSTGRES_PASSWORD: postgres
         options: >-
@@ -73,11 +74,14 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-addons -n 1
     - name: Upload report
+      if: success() || failure()    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
 
   website:
     runs-on: ubuntu-20.04
     needs: build-cache
+    permissions:
+      checks: write
     services:
       postgres:
         image: postgres
@@ -118,11 +122,14 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-website -n 1
     - name: Upload report
+      if: success() || failure()    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
 
   api1_and_js:
     runs-on: ubuntu-20.04
     needs: build-cache
+    permissions:
+      checks: write
     services:
       postgres:
         image: postgres
@@ -166,11 +173,14 @@ jobs:
       - name: Run test
         run: python3 -m invoke test-travis-api1-and-js -n 1
       - name: Upload report
+        if: success() || failure()    # run this step even if previous step failed
         uses: ./.github/actions/gen-report
 
   api2:
     runs-on: ubuntu-20.04
     needs: build-cache
+    permissions:
+      checks: write
     services:
       postgres:
         image: postgres
@@ -211,10 +221,13 @@ jobs:
     - name: Run tests
       run: python3 -m invoke test-travis-api2 -n 1
     - name: Upload report
+      if: success() || failure()    # run this step even if previous step failed
       uses: ./.github/actions/gen-report
 
   api3_and_osf:
     runs-on: ubuntu-20.04
+    permissions:
+      checks: write
     needs: build-cache
     services:
       postgres:
